local text_original = LocalizationManager.text
local testAllStrings = false

function LocalizationManager:text(string_id, ...)
return string_id == "heist_jewelry_store" and "Pipe Store"
or string_id == "heist_four_stores" and "Four Pipes"
or string_id == "heist_nightclub" and "Pipeclub"
or string_id == "heist_mallcrasher" and "Pipecrasher"
or string_id == "heist_ukrainian_job" and "Ukrainian Pipe"
or string_id == "heist_branchbank_deposit" and "Bank Pipe: Deposit"
or string_id == "heist_branchbank_cash" and "Bank Pipe: Cash"
or string_id == "heist_branchbank" and "Bank Pipe"
or string_id == "heist_branchbank_gold" and "Pipe Heist: Gold"
or string_id == "heist_firestarter" and "Pipestarter"
or string_id == "heist_alex" and "Pipe Rats"
or string_id == "heist_watchdogs" and "Pipedogs"
or string_id == "heist_framing_frame" and "Framing Pipe"
or string_id == "heist_welcome_to_the_jungle" and "Pipe Oil"
or string_id == "heist_family" and "Diamond Pipe"
or string_id == "heist_election_day" and "Pipe Day"
or string_id == "heist_arm_fac" and "Pipe Transport: Harbor"
or string_id == "heist_arm_par" and "Pipe Transport: Park"
or string_id == "heist_arm_hcm" and "Pipe Transport: Downtown"
or string_id == "heist_arm_und" and "Pipe Transport: Underpass"
or string_id == "heist_arm_cro" and "Pipe Transport: Crossroads"
or string_id == "heist_arm_for" and "Pipe Transport: Train Heist"
or string_id == "heist_big" and "The Big Pipe"
or string_id == "heist_mia" and "Pipe Miami"
or string_id == "heist_gallery" and "Pipe Gallery"
or string_id == "heist_hox" and "Pipe Breakout"
or string_id == "heist_hox2" and "Pipe Revenge"
or string_id == "cn_menu_community" and "Pipe Community"
or string_id == "heist_pines" and "White Pipe"
or string_id == "heist_cage" and "Car Pipe"
or string_id == "heist_mus" and "Pipe Diamond"
or string_id == "heist_crojob1" and "The Pipe: Dockyard"
or string_id == "heist_crojob2" and "The Pipe: Forest"
or string_id == "heist_rat" and "Cook Pipes"
or string_id == "heist_shoutout_raid" and "Pipedown"
or string_id == "heist_roberts" and "Pipedown"
or string_id == "heist_shoutout_raid" and "Pipedown"
or string_id == "heist_contact_bain" and "Pipe Bain"
or string_id == "heist_contact_vlad" and "Pipe Vlad"
or string_id == "heist_contact_the_elephant" and "Pipe Elephant"
or string_id == "heist_contact_hector" and "Pipe Hector"
or string_id == "heist_contact_the_dentist" and "Pipe Dentist"
or string_id == "heist_kosugi" and "Pipe Raid"
or string_id == "heist_arena" and "The Alesso Pipe"
or string_id == "heist_contact_the_dentist" and "Pipe Dentist"
or string_id == "heist_safehouse" and "The Pipe House"
or string_id == "heist_kenaz" and "Golden Pipe Casino"
or string_id == "heist_jolly" and "Pipeshock"
or string_id == "heist_cane" and "Santa's Pipe"
or string_id == "heist_red2" and "First World Pipe"
or string_id == "heist_dinner" and "Slaughterpipe"
or string_id == "heist_pbr" and "Beneath The Pipe"
or string_id == "heist_pbr2" and "Birth Of Pipe"
or string_id == "heist_pal" and "Counterpipe"
or string_id == "heist_nail" and "Lab Pipes"
or string_id == "heist_man" and "Pipecover"
or string_id == "heist_dark" and "Pipe Station"
or string_id == "heist_mad" and "Pipe Point"
or string_id == "heist_born" and "Lion's Pipe"
or string_id == "heist_chew" and "Pipe Interception"
or string_id == "heist_chill" and "Pipehouse"
or string_id == "heist_chill_combat" and "Pipehouse Raid"
or string_id == "heist_friend" and "Pipe Mansion"
or string_id == "heist_flat" and "Panic Pipe"
or string_id == "heist_help" and "Prison Pipe"
or string_id == "heist_haunted" and "Pipe house Nightmare"
or string_id == "heist_moon" and "Stealing Pipe"
or string_id == "heist_spa" and "Pipe 10-10"
or string_id == "heist_fish" and "The Yacht Pipe"
or string_id == "heist_run" and "Pipe Street"
or string_id == "heist_glace" and "Green Pipe"
or string_id == "heist_dah" and "Diamond Pipe Heist"
or string_id == "heist_hvh" and "Cursed Pipe Room"
or string_id == "heist_wwh" and "Alaskan Pipe"
or string_id == "heist_brb" and "Brooklyn Pipe"
or string_id == "heist_tag" and "Breakin' Pipes"
or string_id == "heist_des" and "Henry's Pipe"
or string_id == "heist_nmh" and "No Pipe (Flashback)"
or string_id == "heist_sah" and "Pipe Auction"
or string_id == "heist_vit" and "The White Pipe"
or string_id == "heist_bph" and "Pipe's Island"
or string_id == "heist_bex" and "San Martín Pipe"
or string_id == "heist_pex" and "Pipe in Tijuana"
or string_id == "heist_fex" and "Buluc's Pipe"
or string_id == "heist_chas" and "Dragon Pipe"
or string_id == "heist_sand" and "The Ukrainian Pipe"
or string_id == "heist_chca" and "Black Pipe"
or string_id == "heist_pent" and "Pipe Master"
or string_id == "heist_ranc" and "Pipe Ranch"
or string_id == "heist_trai" and "Lost in Pipe"









or testAllStrings == true and string_id
or text_original(self, string_id, ...)
end